[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_APPWRITE_ENDPOINT = ""
  NEXT_PUBLIC_APPWRITE_PROJECT_ID = ""
  NEXT_PUBLIC_APPWRITE_DATABASE_ID = ""
  NEXT_PUBLIC_APPWRITE_COLLECTION_ID = ""