name: Deploy Appwrite Functions

on:
  push:
    branches: [ master, main ]
    paths:
      - 'functions/**'
  workflow_dispatch:

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Appwrite CLI
      run: npm install -g appwrite-cli
    
    - name: Login to Appwrite
      run: |
        appwrite login --endpoint ${{ secrets.APPWRITE_ENDPOINT }} \
                      --email ${{ secrets.APPWRITE_EMAIL }} \
                      --password ${{ secrets.APPWRITE_PASSWORD }}
    
    - name: Set Appwrite Project
      run: appwrite init project --project-id ${{ secrets.APPWRITE_PROJECT_ID }}
    
    - name: Deploy Scrape Function
      run: |
        cd functions/scrape
        appwrite deploy function \
          --function-id scrape-function \
          --name "Content Scraper" \
          --runtime "node-18.0" \
          --entrypoint "src/main.js" \
          --commands "npm install" "apt-get update" "apt-get install -y python3 python3-pip" "pip3 install trafilatura yt-dlp"
    
    - name: Deploy MCP Function
      run: |
        cd functions/mcp
        appwrite deploy function \
          --function-id mcp-server \
          --name "MCP Server" \
          --runtime "node-18.0" \
          --entrypoint "src/main.js" \
          --commands "npm install"
    
    - name: Set Function Variables
      run: |
        # Set environment variables for scrape function
        appwrite functions updateVariable \
          --function-id scrape-function \
          --key APPWRITE_API_KEY \
          --value ${{ secrets.APPWRITE_API_KEY }}
        
        appwrite functions updateVariable \
          --function-id scrape-function \
          --key APPWRITE_DATABASE_ID \
          --value ${{ secrets.APPWRITE_DATABASE_ID }}
        
        appwrite functions updateVariable \
          --function-id scrape-function \
          --key APPWRITE_COLLECTION_ID \
          --value ${{ secrets.APPWRITE_COLLECTION_ID }}
        
        # Set environment variables for MCP function
        appwrite functions updateVariable \
          --function-id mcp-server \
          --key APPWRITE_API_KEY \
          --value ${{ secrets.APPWRITE_API_KEY }}
        
        appwrite functions updateVariable \
          --function-id mcp-server \
          --key APPWRITE_DATABASE_ID \
          --value ${{ secrets.APPWRITE_DATABASE_ID }}
        
        appwrite functions updateVariable \
          --function-id mcp-server \
          --key APPWRITE_COLLECTION_ID \
          --value ${{ secrets.APPWRITE_COLLECTION_ID }}